#!/usr/bin/env node

/**
 * Smoke test for mcptoolshop.com
 *
 * Split into two tiers:
 * - COMMITTED: pages built from committed data (always pass locally + CI)
 * - CI_GENERATED: pages built from CI-only outputs (only pass after deploy)
 *
 * Usage:
 *   node scripts/smoke-test.mjs                        # committed only
 *   node scripts/smoke-test.mjs --all                  # committed + CI-generated
 *   node scripts/smoke-test.mjs http://localhost:4321   # test local dev
 */

const args = process.argv.slice(2);
const includeGenerated = args.includes("--all");
const BASE = args.find((a) => a.startsWith("http")) || "https://mcptoolshop.com";

// ── Committed artifact checks ───────────────────────────────────
// These pages are rendered from data committed to the repo.
// They must work both locally and in CI.
const COMMITTED = [
  // Core pages
  { url: "/", expect: 200, label: "homepage" },
  { url: "/tools/", expect: 200, label: "tools index" },
  { url: "/releases/", expect: 200, label: "releases page" },
  { url: "/about/", expect: 200, label: "about page" },
  { url: "/trust/", expect: 200, label: "trust page" },
  { url: "/support/", expect: 200, label: "support page" },

  // Lab pages (rendered from committed data)
  { url: "/lab/", expect: 200, label: "lab index" },
  { url: "/lab/marketir/", expect: 200, label: "lab: marketir preview" },
  { url: "/lab/signals/", expect: 200, label: "lab: signals dashboard" },
  { url: "/lab/ops/", expect: 200, label: "lab: ops dashboard" },
  { url: "/lab/worthy/", expect: 200, label: "lab: worthy scorecards" },
  { url: "/lab/baseline/", expect: 200, label: "lab: pipeline baseline" },
  { url: "/lab/promo/", expect: 200, label: "lab: promo calendar" },

  // Static assets (committed to repo)
  { url: "/favicon.svg", expect: 200, label: "favicon" },

  // Trust receipt (committed)
  { url: "/trust.json", expect: 200, label: "trust receipt JSON" },
];

// ── CI-generated checks ─────────────────────────────────────────
// These pages/files are generated by CI workflows (presskit, outreach,
// links, go-links, campaigns, snippets, partners). They only exist
// after a full CI build + deploy. Skipped by default.
const CI_GENERATED = [
  // Tool pages (dynamic, require registered tools in projects.json)
  { url: "/tools/backpropagate/", expect: 200, label: "tool page: backpropagate" },
  { url: "/tools/comfy-headless/", expect: 200, label: "tool page: comfy-headless" },

  // Legacy redirects
  { url: "/brain-dev.html", expect: 200, label: "legacy: brain-dev.html" },
  { url: "/registry.html", expect: 200, label: "legacy: registry.html" },
  { url: "/voice-soundboard.html", expect: 200, label: "legacy: voice-soundboard.html" },

  // Marketing outputs (generated from MarketIR — gitignored)
  { url: "/links.json", expect: 200, label: "link registry" },

  // Build metadata
  { url: "/_build.json", expect: 200, label: "build metadata" },
];

// ── Run checks ──────────────────────────────────────────────────
const checks = includeGenerated
  ? [...COMMITTED, ...CI_GENERATED]
  : COMMITTED;

let passed = 0;
let failed = 0;

console.log(
  `Smoke test: ${checks.length} checks (${includeGenerated ? "committed + CI-generated" : "committed only"})`
);
console.log(`Target: ${BASE}\n`);

for (const check of checks) {
  const url = `${BASE}${check.url}`;
  try {
    const res = await fetch(url, { redirect: "follow" });
    if (res.status === check.expect) {
      console.log(`  ✓ ${check.label} (${res.status})`);
      passed++;
    } else {
      console.error(
        `  ✗ ${check.label}: expected ${check.expect}, got ${res.status}`
      );
      failed++;
    }
  } catch (err) {
    console.error(`  ✗ ${check.label}: ${err.message}`);
    failed++;
  }
}

// ── Build freshness (warning only, never fails) ─────────────────
if (includeGenerated) {
  try {
    const buildRes = await fetch(`${BASE}/_build.json`);
    if (buildRes.ok) {
      const build = await buildRes.json();
      const age = Date.now() - new Date(build.builtAt).getTime();
      const hours = Math.round(age / 3600000);
      console.log(`\n  Build: commit ${build.commit}, ${hours}h old, ${build.projects} projects`);
      if (hours > 24) console.warn(`  ⚠ Build is ${hours}h old`);
    }
  } catch {
    /* skip */
  }
}

// ── Summary ─────────────────────────────────────────────────────
console.log(`\n${passed} passed, ${failed} failed out of ${checks.length} checks`);
if (failed > 0) process.exit(1);
